alias: Office light off - no precense
description: |
  Sammuta valot jos ei ole havaittu henkilöä työhuneessa
triggers:
  - type: not_occupied
    device_id: b093d59a6daf0796860829e543018549
    entity_id: 569217a36ecb17274ff3296fc791ec1f
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 10
      seconds: 0
conditions: []
actions:
  - action: light.turn_off
    metadata: {}
    data:
      transition: 14
    target:
      entity_id: light.office_main_light
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.ikea_power_switch_1
mode: single
