alias: WallSwitch - Buttons 1 & 2 Office Main Light (mode switch + off on double)
triggers:
  - topic: zigbee2mqtt/wallSwitch_fourButtons
    value_template: "{{ value_json.action }}"
    payload: 1_single
    id: b1_single
    trigger: mqtt
  - topic: zigbee2mqtt/wallSwitch_fourButtons
    value_template: "{{ value_json.action }}"
    payload: 2_single
    id: b2_single
    trigger: mqtt
  - topic: zigbee2mqtt/wallSwitch_fourButtons
    value_template: "{{ value_json.action }}"
    payload: 1_double
    id: b1_double
    trigger: mqtt
  - topic: zigbee2mqtt/wallSwitch_fourButtons
    value_template: "{{ value_json.action }}"
    payload: 2_double
    id: b2_double
    trigger: mqtt
actions:
  - variables:
      light_entity: light.office_main_light
      last_button_helper: input_text.office_last_button
      pressed_button: >-
        {% if trigger.id in ['b1_single','b1_double'] %} button_1 {% else %}
        button_2 {% endif %}
      is_double: "{{ trigger.id in ['b1_double','b2_double'] }}"
      is_on: "{{ is_state(light_entity, 'on') }}"
      last_button: "{{ states(last_button_helper) | trim }}"
      target_brightness: "{% if pressed_button == 'button_1' %} 100 {% else %} 5 {% endif %}"
      target_ct: "{% if pressed_button == 'button_1' %} 4092 {% else %} 2585 {% endif %}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_double }}"
        sequence:
          - target:
              entity_id: "{{ light_entity }}"
            data:
              transition: 2
            action: light.turn_off
          - target:
              entity_id: "{{ last_button_helper }}"
            data:
              value: ""
            action: input_text.set_value
      - conditions:
          - condition: template
            value_template: >-
              {{ (not is_double) and is_on and (last_button == pressed_button)
              }}
        sequence:
          - target:
              entity_id: "{{ light_entity }}"
            data:
              transition: 2
            action: light.turn_off
          - target:
              entity_id: "{{ last_button_helper }}"
            data:
              value: ""
            action: input_text.set_value
    default:
      - target:
          entity_id: "{{ light_entity }}"
        data:
          brightness_pct: "{{ target_brightness }}"
          color_temp_kelvin: "{{ target_ct }}"
          transition: 2
        action: light.turn_on
      - target:
          entity_id: "{{ last_button_helper }}"
        data:
          value: "{{ pressed_button }}"
        action: input_text.set_value
mode: single
